Repository shardeum/lib-types, pull requests merged in 2024-09, with the labels that each got.

#18 RED-268: add cycle to unjoin request
  src/p2p/JoinTypes.ts
Labels: Review effort [1-5]: 2

#16 RED-201: Network Generated Transactions
  src/index.ts
  src/p2p/CycleCreatorTypes.ts
  src/p2p/P2PTypes.ts
  src/p2p/ServiceQueueTypes.ts
Labels: Review effort [1-5]: 3

#21 RED-258: add types for shutdown handler refactor
  src/p2p/ServiceQueueTypes.ts
Labels: Review effort [1-5]: 1
